### Test hello world
GET http://localhost:5000/

### Get users
GET http://localhost:5000/api/users/

### Get user
GET http://localhost:5000/api/users/2

###
POST http://localhost:5000/api/users HTTP/1.1
content-type: application/json

{
  "create":  {
    "email": "Jane@gmail.com",
    "name": "Jane Carry",
    "gender": "female",
    "age": 34,
    "height": 167,
    "weight": 50
  }
}

###
POST http://localhost:5000/api/users HTTP/1.1
content-type: application/json

{
 "a": "1"
}
###
PATCH http://localhost:5000/api/users/4 HTTP/1.1
content-type: application/json

{
  "update": {
    "email": "Jane2@gmail.com",
    "name": "Jane2 Carry",
    "gender": "female",
    "age": 35,
    "height": 168,
    "weight": 52
  }
}
###
PATCH http://localhost:5000/api/users/3 HTTP/1.1
content-type: application/json

{
  "update": {
    "name": "user101"
  }
}

###
PATCH http://localhost:5000/api/users/22 HTTP/1.1
content-type: application/json

{
  "update": {
    "description": "User 101 description."
  }
}
###
DELETE http://localhost:5000/api/users/4

