### Test hello world
GET http://localhost:5000/

### Get meals
GET http://localhost:5000/api/meals/1

### Get meal
GET http://localhost:5000/api/meals/1/1

### Create meal
POST http://localhost:5000/api/meals/1 HTTP/1.1
content-type: application/json

{
  "create": {
    "name": "Meal 4   ",
    "description": "Meal 100 description.",
    "userId": 1,
    "planId": 2
  }
}

### Error: create meal without parameters 
POST http://localhost:5000/api/meals/1 HTTP/1.1
content-type: application/json

{
}

### Update a meal
PATCH http://localhost:5000/api/meals/1/2 HTTP/1.1
content-type: application/json

{
  "update": {
    "name": "Meal 4.2   ",
    "description": "Meal 102 description.",
    "userId": 1,
    "planId": 2
  }
}

### Error: Update a meal without parameters
PATCH http://localhost:5000/api/meals/1/2 HTTP/1.1
content-type: application/json

{
  "update": {
  }
}

### Error: Update a meal that doesn't exist
PATCH http://localhost:5000/api/meals/1/1000 HTTP/1.1
content-type: application/json

{
  "update": {
    "name": "Meal 4.2   ",
    "description": "Meal 102 description.",
    "userId": 1,
    "planId": 2
  }
}

### Error: Update a meal so that user doesn't exist
PATCH http://localhost:5000/api/meals/1000/2 HTTP/1.1
content-type: application/json

{
  "update": {
    "name": "Meal 4.2   ",
    "description": "Meal 102 description.",
    "userId": 1,
    "planId": 2
  }
}

### Delete a meal
DELETE http://localhost:5000/api/meals/1/3

### Error: Delete a meal that doesn't exist
DELETE http://localhost:5000/api/meals/1/100

### Error: Delete a meal so that user doesn't exist
DELETE http://localhost:5000/api/meals/1000/4

