### Test hello world
GET http://localhost:5000/

### Get all users plans
GET http://localhost:5000/api/plans
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVzZXJJZCI6NywiZW1haWwiOiJKaWxsQGdtYWlsLmNvbSIsIm5hbWUiOiJKaWxsIENhcnJ5In0sImlhdCI6MTU4MDExNzg5MiwiZXhwIjoxNTgwMTQ2NjkyfQ.fsn1JGvDVtXsy5-UEzz2ndMxiqadGlAEjUPuQJdfjOE

### Get one user's plan
GET http://localhost:5000/api/plans/15
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVzZXJJZCI6NywiZW1haWwiOiJKaWxsQGdtYWlsLmNvbSIsIm5hbWUiOiJKaWxsIENhcnJ5In0sImlhdCI6MTU4MDAzNjY3MSwiZXhwIjoxNTgwMDY1NDcxfQ.Zevk8kdjXwwQPH7-uKcsSt6C-hVdMIjZZTu170giGnE

### Error: Plan not found
GET http://localhost:5000/api/plans/1000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVzZXJJZCI6NywiZW1haWwiOiJKaWxsQGdtYWlsLmNvbSIsIm5hbWUiOiJKaWxsIENhcnJ5In0sImlhdCI6MTU4MDAzNjY3MSwiZXhwIjoxNTgwMDY1NDcxfQ.Zevk8kdjXwwQPH7-uKcsSt6C-hVdMIjZZTu170giGnE

### Error: JWT not set to header
GET http://localhost:5000/api/plans/6

###  Create plan
POST http://localhost:5000/api/plans/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVzZXJJZCI6NywiZW1haWwiOiJKaWxsQGdtYWlsLmNvbSIsIm5hbWUiOiJKaWxsIENhcnJ5In0sImlhdCI6MTU4MDAzNjY3MSwiZXhwIjoxNTgwMDY1NDcxfQ.Zevk8kdjXwwQPH7-uKcsSt6C-hVdMIjZZTu170giGnE
content-type: application/json

{
  "newPlan": {
    "name": "  aaaa 2  ",
    "description": "  Plan 100 description."
  }
}

### Error: Create plan. JWT not set
POST http://localhost:5000/api/plans/ HTTP/1.1
content-type: application/json

{
  "newPlan": {
    "name": "  plan name   ",
    "description": "  Plan 100 description."
  }
}

### Error: Create plan. Name not given
POST http://localhost:5000/api/plans/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVzZXJJZCI6NywiZW1haWwiOiJKaWxsQGdtYWlsLmNvbSIsIm5hbWUiOiJKaWxsIENhcnJ5In0sImlhdCI6MTU4MDAzNjY3MSwiZXhwIjoxNTgwMDY1NDcxfQ.Zevk8kdjXwwQPH7-uKcsSt6C-hVdMIjZZTu170giGnE

content-type: application/json

{
  "newPlan": {
  }
}

### Update plan succesfully
PATCH http://localhost:5000/api/plans/17 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVzZXJJZCI6NywiZW1haWwiOiJKaWxsQGdtYWlsLmNvbSIsIm5hbWUiOiJKaWxsIENhcnJ5In0sImlhdCI6MTU4MDAzNjY3MSwiZXhwIjoxNTgwMDY1NDcxfQ.Zevk8kdjXwwQPH7-uKcsSt6C-hVdMIjZZTu170giGnE
 
{
  "plan": {
    "name": "  Updated name   ",
    "description": "  Updated description."
  }
}

### Error: plan not found
PATCH http://localhost:5000/api/plans/4 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVzZXJJZCI6NywiZW1haWwiOiJKaWxsQGdtYWlsLmNvbSIsIm5hbWUiOiJKaWxsIENhcnJ5In0sImlhdCI6MTU4MDAzNjY3MSwiZXhwIjoxNTgwMDY1NDcxfQ.Zevk8kdjXwwQPH7-uKcsSt6C-hVdMIjZZTu170giGnE

{
  "plan": {
    "name": "  Updated name  2 ",
    "description": "  Updated description."
  }
}

### Error: plan values not given
PATCH http://localhost:5000/api/plans/4 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVzZXJJZCI6NywiZW1haWwiOiJKaWxsQGdtYWlsLmNvbSIsIm5hbWUiOiJKaWxsIENhcnJ5In0sImlhdCI6MTU4MDAzNjY3MSwiZXhwIjoxNTgwMDY1NDcxfQ.Zevk8kdjXwwQPH7-uKcsSt6C-hVdMIjZZTu170giGnE

{
  "plan": {
  }
}

### Delete succesfully
DELETE http://localhost:5000/api/plans/19
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVzZXJJZCI6NywiZW1haWwiOiJKaWxsQGdtYWlsLmNvbSIsIm5hbWUiOiJKaWxsIENhcnJ5In0sImlhdCI6MTU4MDAzNjY3MSwiZXhwIjoxNTgwMDY1NDcxfQ.Zevk8kdjXwwQPH7-uKcsSt6C-hVdMIjZZTu170giGnE

### Error: Delete without JWT
DELETE http://localhost:5000/api/plans/4

### Error: Delete with unexisting planId
DELETE http://localhost:5000/api/plans/1000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVzZXJJZCI6NywiZW1haWwiOiJKaWxsQGdtYWlsLmNvbSIsIm5hbWUiOiJKaWxsIENhcnJ5In0sImlhdCI6MTU4MDAzNjY3MSwiZXhwIjoxNTgwMDY1NDcxfQ.Zevk8kdjXwwQPH7-uKcsSt6C-hVdMIjZZTu170giGnE

