### Test hello world
GET http://localhost:5000/

### Get user information with JWT token
GET http://localhost:5000/api/users/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVzZXJJZCI6NywiZW1haWwiOiJKaWxsQGdtYWlsLmNvbSIsIm5hbWUiOiJKaWxsIENhcnJ5In0sImlhdCI6MTU4MDExNzg5MiwiZXhwIjoxNTgwMTQ2NjkyfQ.fsn1JGvDVtXsy5-UEzz2ndMxiqadGlAEjUPuQJdfjOE

### Get a user
GET http://localhost:5000/api/users/2

### Get a user
GET http://localhost:5000/api/users/cecilia@a.com/123456

### Error: Get user which doesn't exists
GET http://localhost:5000/api/users/1000

### Create user
POST http://localhost:5000/api/users/create HTTP/1.1
content-type: application/json

{
  "newUser":  {
    "email": "Jill3@gmail.com",
    "password": "123456",
    "name": "Jill Carry",
    "gender": "female",
    "age": 33,
    "height": 163,
    "weight": 53
  }
}

###  Error: Try to create user without params
POST http://localhost:5000/api/users HTTP/1.1
content-type: application/json

{
}

### Login user
POST http://localhost:5000/api/users/signin HTTP/1.1
content-type: application/json

{
  "user":  {
    "email": "Jill@gmail.com",
    "password": "123456"
  }
}

/api/users/signin


### Update user
PATCH http://localhost:5000/api/users/2 HTTP/1.1
content-type: application/json

{
  "update": {
    "email": "Jane2@gmail.com",
    "name": "Jane2 Carry",
    "gender": "female",
    "age": 35,
    "height": 168,
    "weight": 52
  }
}
### Error: Update user without params
PATCH http://localhost:5000/api/users/3 HTTP/1.1
content-type: application/json

{
  "update": {
  }
}

### Error: Try to update user that doesn't exists
PATCH http://localhost:5000/api/users/1000 HTTP/1.1
content-type: application/json

{
  "update": {
    "email": "Jane2@gmail.com",
    "name": "Jane2 Carry",
    "gender": "female",
    "age": 35,
    "height": 168,
    "weight": 52
  }
}
### Delete a user
DELETE http://localhost:5000/api/users/5

### Error: Try to delete a user that doesn't exsist
DELETE http://localhost:5000/api/users/1000

### Error: Try to delete a user that has plans
DELETE http://localhost:5000/api/users/1